service: optimizelys-harsh-mistress

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  profile: ${opt:profile}
#  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Query"
        - "dynamodb:GetRecords"
        - "dynamodb:GetShardIterator"
        - "dynamodb:DescribeStream"
        - "dynamodb:ListStreams"

  environment:
    OPTIMIZELY_KEY: ${env:OPTIMIZELY_KEY}

package:
  exclude:
    - "**"
  include:
    - output/**
    - node_modules/**
    - index.js


functions:
  retrieveWeights:
    handler: index.retrieveWeights
    events:
      - schedule: rate(1 hour)
  adjustABTests:
    handler: index.adjustABTests
    events:
      - stream: arn:aws:dynamodb:us-east-1:421555867712:table/experiments-prod/stream/2017-05-18T00:37:39.910
          # type: dynamodb
          # arn:
          #   Fn::GetAtt:
          #     - experiments
          #     - Arn


resources:
  Resources:
    experiments:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: 'experiments-${opt:stage, self:provider.stage}'
        AttributeDefinitions:
          - AttributeName: keyname
            AttributeType: S
          - AttributeName: retrievetime
            AttributeType: S
        KeySchema:
          - AttributeName: keyname
            KeyType: HASH
          - AttributeName: retrievetime
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
